version: "3.3"

services:
  papyrus-server:
    image: egalletta/papyrus-server:1.0.0-development
    restart: always
    networks:
      - public
      - db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nugget.entrypoints=web-secured"
        - "traefik.http.routers.nugget.rule=Host(`papyrus.galletta.xyz`)"
        - "traefik.http.routers.nugget.tls=true"
        - "traefik.http.services.nugget.loadbalancer.server.port=80"
  papyrus-scraper:
    image: egalletta/papyrus-scraper:1.0.0-development
    restart: always
    networks:
        - db
  mongo:
    image: mongo:latest
    networks:
      - db
networks:
  public:
    external: true

